### PR TITLE
Fix erroneus components bug

### LINKED ISSUE #206: Uploading PDF by URL creates duplicate components
### Description

Both plainly calling the `/data/update` endpoint and pasting a pdf url in the webui creates a duplicate component in the manifest. Since it happens on direct upload with the backen, it's not a frontend issue. 

@kadamidev suspects its erroneous logic around directory wrapping of the uploaded file.

```json
{
  "authors": [],
  "components": [
    {
      "id": "root",
      "name": "root",
      "payload": {
        "cid": "bafybeicrsddlvfbbo5s3upvjbtb5flc73iupxfy2kf3rv43kkbvegbqbwq",
        "path": "root"
      },
      "type": "data-bucket"
    },
    {
      "id": "a657669c-3f2c-48dc-8881-183a545a9d92",
      "name": "2207.11136.pdf",
      "payload": {
        "externalUrl": "https://arxiv.org/pdf/2207.11136.pdf",
        "path": "root/2207.11136.pdf",
        "url": "bafybeibvegnoncvqylnuaye7uhguoc2blzzme2mlykegnt3yhhw4n5xphi"
      },
      "starred": false,
      "subtype": "research-article",
      "type": "pdf"
    },
    {
      "id": "962116a6-fb65-4529-8629-ffce7a2446cb",
      "name": "",
      "payload": {
        "externalUrl": "https://arxiv.org/pdf/2207.11136.pdf",
        "path": "root/",
        "url": "bafybeichzcg6bhh67zs4t5byojgp676no4jsbe666nh3vwsq72rhkslnva"
      },
      "starred": false,
      "subtype": "research-article",
      "type": "pdf"
    }
  ],
  "defaultLicense": "CC BY",
  "researchFields": [],
  "title": "My Node",
  "version": "desci-nodes-0.2.0"
}
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by kadamidev**
Closes #206 

## Description of the Problem / Feature
- Handling of repos was getting in the way of the logic for uploading single files with external URLS (pdfs), resulting in additional erroneous manifest component entries for PDFs
## Explanation of the solution
- Dir wrapping for single files was found to cause the issue, separating a part of the flow between single files/multiple fixed it.

### CODE REVIEW

File: desci-server/src/services/data/externalUrlProcessing.ts [hunk 1]
```diff
@@ -155,7 +157,7 @@ export async function processExternalUrlDataToIpfs({
     // Pin new files, add draftNodeTree entries
     if (externalUrlFiles?.length) {
       // External URL non-repo
-      pinResult = await pinNewFiles(externalUrlFiles, true);
```
Comment (m0ar) [inline desci-server/src/services/data/externalUrlProcessing.ts:158]: lol I'm dying to refactor this function into like 5 different ones for all these cases :joy:

**Review by m0ar — APPROVED** [review]
Looks aight, I think :eyes: :pray:

File: desci-server/src/controllers/data/update.ts [hunk 2]
```diff
@@ -24,7 +24,10 @@ export interface ErrorResponse {
 export const update = async (req: RequestWithNode, res: Response<UpdateResponse | ErrorResponse | string>) => {
   const owner = req.user;
   let node = req.node;
-  const { uuid, manifest: draftManifest, contextPath, componentType, componentSubtype, newFolderName } = req.body;
+  const { uuid, manifest: draftManifest, componentType, componentSubtype, newFolderName } = req.body;
+  let { contextPath } = req.body;
```
Comment (m0ar) [inline desci-server/src/controllers/data/update.ts:28]: nitpick but I'm not a fan of overwriting variables, if I saw this somewhere and I see it's passed in the request body I'd assume it hasn't been messed with :eyes: 

I'd deconstruct like the others, then bind the result of the clean to `const cleanContextPath` or smt :angel:
